### ISSUE TITLE
ddollar/heroku-buildpack-multiをやめる

### ISSUE THREAD

**Issue by KOBA789** [masawada/cabocha-api#2]
最新の dokku だと `.buildpacks` を検出して自動で複数の buildpack を利用します。

https://github.com/ddollar/heroku-buildpack-multi は deprecated になっているので、README を修正し、 `BUILDPACK_URL` に関する記述を削除してもいいかと思います。

**Comment by masawada** [comment]
built-in buildpack-multi supportなるほど〜
完全に追えてなかった… 修正します:pray:
